[versions]
# @keep
carrot2 = "4.8.0-SNAPSHOT"
# @keep
node = "18.18.2"
# @keep
yarn = "1.22.19"
carrotsearch-console = "1.2.0"
jackson = "2.19.1"
jetty = "11.0.25"
log4j = "2.24.3"
lucene = "10.2.2"
# @keep This is the minimum required Java version.
minJava = "21"
# @keep This is GJF version for spotless/ tidy.
googleJavaFormat = "1.27.0"
# @keep spotless formatting of groovy/gradle files
greclipse = "4.26"
proguard = "7.7.0"

[libraries]
bytebuddy = "net.bytebuddy:byte-buddy:1.17.5"
assertj = "org.assertj:assertj-core:4.0.0-M1"
carrotsearch-console-formatters = { module = "com.carrotsearch.console:formatters", version.ref = "carrotsearch-console" }
carrotsearch-console-launcher = { module = "com.carrotsearch.console:launcher", version.ref = "carrotsearch-console" }
carrotsearch-console-testing = { module = "com.carrotsearch.console:testing", version.ref = "carrotsearch-console" }
carrotsearch-hppc = "com.carrotsearch:hppc:0.10.0"
carrotsearch-procfork = "com.carrotsearch:procfork:1.0.6"
carrotsearch-progresso-jvmversion = "com.carrotsearch.progresso:progresso-jvmversion:1.8.3"
commons-compress = "org.apache.commons:commons-compress:1.24.0"
commons-text = "org.apache.commons:commons-text:1.13.1"
httpclient = "org.apache.httpcomponents:httpclient:4.5.14"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version.ref = "jetty" }
jetty-webapp = { module = "org.eclipse.jetty:jetty-webapp", version.ref = "jetty" }
jetty-toolchain-servlet-api = "org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api:5.0.2"
jflex = "de.jflex:jflex:1.9.1"
junit = "junit:junit:4.13.2"
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2 = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
lucene-core = { module = "org.apache.lucene:lucene-core", version.ref = "lucene" }
lucene-analysis-common = { module = "org.apache.lucene:lucene-analysis-common", version.ref = "lucene" }
lucene-analysis-icu = { module = "org.apache.lucene:lucene-analysis-icu", version.ref = "lucene" }
lucene-analysis-kuromoji = { module = "org.apache.lucene:lucene-analysis-kuromoji", version.ref = "lucene" }
lucene-analysis-nori = { module = "org.apache.lucene:lucene-analysis-nori", version.ref = "lucene" }
lucene-analysis-smartcn = { module = "org.apache.lucene:lucene-analysis-smartcn", version.ref = "lucene" }
lucene-queries = { module = "org.apache.lucene:lucene-queries", version.ref = "lucene" }
lucene-queryparser = { module = "org.apache.lucene:lucene-queryparser", version.ref = "lucene" }
lucene-testFramework = { module = "org.apache.lucene:lucene-test-framework", version.ref = "lucene" }
mockito-core = "org.mockito:mockito-core:5.18.0"
morfologik-polish = "org.carrot2:morfologik-polish:2.1.9"
randomizedtesting-runner = "com.carrotsearch.randomizedtesting:randomizedtesting-runner:2.8.3"
slf4j-api = "org.slf4j:slf4j-api:2.0.17"
proguard-gradle = { module = "com.guardsquare:proguard-gradle", version.ref = "proguard" }

[plugins]
node-gradle = "com.github.node-gradle.node:7.1.0"
buildinfra = "com.carrotsearch.gradle.buildinfra:0.0.16"